# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 归档页
archive:
  banner_img: /img/wallhaven.png

# 分类页
category:
  banner_img: /img/wallhaven.png
  collapse_depth: 1

#关于页
about:
  banner_img: /img/wallhaven.png
  avatar: /img/man.svg
  name: "Alan"
  intro: "我是Alan,一名程序猿"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/AlanJava', tip: 'GitHub' }
#自定义页
page:
  banner_img: /img/wallhaven.png
#友链页
links:
  enable: true
  banner_img: /img/wallhaven.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  # 友链的成员项
  items:
    - {
      title: "Fluid Blog",
      intro: "本站使用主题",
      link: "https://hexo.fluid-dev.com/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Repo",
      intro: "Fluid主题 GitHub 仓库",
      link: "https://github.com/fluid-dev/hexo-theme-fluid",
      avatar: "/img/github.png"
    }
# 左上角标题
navbar:
  blog_title: AlanBlog
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

# 首页
index:
  banner_img: /img/wallhaven.png
  slogan:
    enable: true
    text: This is Alan's blog website
    api:
      enable: true
      url: "api/slogan"
      method: "GET"
      headers: { }
      keys: [ "data" ]

# 网页访问统计
web_analytics:  # 网页访问统计
  enable: true # 默认为false，启用网页统计改为true即可
  baidu: https://hm.baidu.com/hm.js?7d37043c4c8a6f686df5c990bb99f544 # 百度统计的Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串

# 页脚
footer:
  # 访问统计
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    # uv_format: "总访客数 {} 人"
  # 页脚文字
  # content:
  #备案信息
  beian:
    enable: true
    # ICP证号
    icp_text: 皖ICP备2022001395号
    # 公安备案号，不填则只显示ICP
    police_text:
    # 公安备案的编号，用于URL跳转查询
    police_code:
    # 公安备案的图片. 为空时不显示备案图片
    police_icon:

# 暗色模式
dark_mode:
  enable: true
  default: auto

# 归档
tag:
  banner_img: /img/wallhaven.png
  tagcloud:
    min_font: 20
# 文章配置
post:
  banner_img: /img/wallhaven.png
  updated:
    enable: true
    # 是否使用相对时间表示，比如："3 天前"
    relative: false
  # 侧边栏展示当前分类下的文章
  category_bar:
    enable: true
    # 开启后，只有在文章 Front-matter 里指定 `category_bar: true` 才会展示分类，也可以通过 `category_bar: ["分类A"]` 来指定分类
    specific: false
    # 置于板块的左侧或右侧
    # Options: left | right
    placement: right
    # 文章的排序字段，前面带减号是倒序，不带减号是正序
    # Options: date | title | or other field of front-matter
    post_order_by: "date"
    # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
    post_limit: 5
  # 侧边栏展示文章目录
  toc:
    enable: true
    # 置于板块的左侧或右侧
    # Options: left | right
    placement: left
    # 目录会选择这些节点作为标题
    headingSelector: "h1,h2,h3,h4,h5,h6"
    # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在下级标题则默认展开
    collapseDepth: 2
  # 许可协议
  copyright:
    enable: true
    license: ""
  # 评论
  comments:
    enable: false
    type: valine
  meta:
    author: # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date: # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: false
      format: "dddd, MMMM Do YYYY, h:mm a"  # 格式参照 ISO-8601 日期格式化
    wordcount: # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read: # 阅读时间
      enable: true
      format: "{} 分钟"
    views: # 阅读次数
      enable: true
      source: "busuanzi"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"
# 评论模块配置
valine:
  appid: NTA7OxVtXSbGVyA1QaonmQf8-MdYXbMMI
  appkey: 5IOcUsMWUOWCU7eaBtBR4TiX
  placeholder: 说点什么
  path: window.location.pathname
  avatar: retro
  meta: ['nick', 'mail', 'link']
  pageSize: 10
  lang: zh-CN
  highlight: true
  recordIP: true
  serverURLs: https://nta7oxvt.api.lncldglobal.com
  mathJax: false

# 一些好玩的功能
fun_features:
  # 为 subtitle 添加打字机效果
  typing:
    enable: true
    # 打印速度，数字越大越慢
    typeSpeed: 40
    # 游标字符
    cursorChar: "|"




# Site
title: AlanBlog
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''
favicon: /img/blog.svg
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://tgkzxy.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
